# -*- encoding: utf-8 -*-

require 'uri'
require_relative 'base'

module WebgenBibtex
  class Tag
    module BibItem
      extend WebgenBibtex::Tag::Base

      def self.call(tag, _, context)
        bib, proc = make_objects(tag, context)
        id = context[:config]['tag.bibliography.key']
        render = proc.render(:bibliography, id: id)[0]
        render = add_url_hyperlinks(context, render)

        bibitem = bib[id]
        linklist = make_linklist(bibitem, context)
        if !linklist.nil? then
          render = render_linklist(linklist, bibitem, context, render)
        end

        render
      end

      private

      def self.make_linklist(bibitem, context)
        # Extracts webgen links from a BibTeX item and parses them into a list
        if bibitem[:webgenlink].nil?
          if bibitem[:url].nil? then return
          else
            # If "Webgenlink" field doesn't exist, but "Url" exists, use that one
            bibentry = bibitem[:url]
          end
        else
          bibentry = bibitem[:webgenlink]
        end
        linklist = Array.new
        # Multiple links should be separated by ||
        entries = bibentry.include?('||') ? bibentry.split("||") : [bibentry]
        entries.each do |entry|
          # Link title and URL should be separated by |
          if entry.include?("|") then
            title, url = entry.split("|")
          else
            title, url = :link, entry
          end
          linklist.push([title.to_sym, resolve_link(url, context)])
        end
        linklist
      end

      def self.resolve_link(url, context)
        # Resolves a link that is either external, or absolute to the project
        if url.include?("://") # URL has protocol -- leave unchanged
          ''
        else
          dest_node = context.ref_node.resolve(url.to_s, context.dest_node.lang, true)
          if dest_node
            context.website.ext.item_tracker.add(context.dest_node, :node_meta_info, dest_node)
            url = context.dest_node.route_to(dest_node)
          end
        end
        url
      end

      def self.render_linklist(linklist, bibitem, context, render)
        # Augments a rendered bibliography entry with links
        linkstyle = context[:config]['tag.bibliography.link_style']
        if linkstyle == "inline" or linkstyle == "both" then
          url = linklist.shift[1]
          render = add_inline_link(url, bibitem, context, render)
        end
        if linkstyle == "append" or linkstyle == "both" then
          linklist.each do |title,url|
            render += " " + make_appended_link(title, url)
          end
        end
        render
      end

      def self.add_inline_link(url, bibitem, context, render)
        # Adds a link to the bibliography entry's title
        # ---
        # I didn't find any way to mark up the title in the HTML generated by
        # citeproc-ruby, so I'm looking for the title string in the generated
        # output.  This might still break when special characters are involved,
        # we will see.
        title = bibitem[:title].to_s.downcase
        title_start = render.downcase.index(title)
        if title_start.nil? then
          context.website.logger.warn [
            "[webgen-bibtex] couldn't find title in bibliography string; inline link not generated",
            "      title is: #{title}",
            "     render is: #{render.downcase}"
          ]
          render
        else
          render[0, title_start] +
            "<a href=\"" + url + "\">" +
            render[title_start, title.length] +
            "</a>" +
            render[title_start + title.length, 1000000]
        end
      end

      def self.make_appended_link(title, url)
        # Make a link to add to the end of the bibliography entry
        return "<a href=\"" + url + "\">" +
               "&#91;" + title.to_s + "&#93;" +
               "</a>"
      end

      def self.add_url_hyperlinks(context, render)
        # Adds hyperlinks to URLs contained in the rendered output
        # ---
        # Note: explicitly added schemes because URI.extract matches very
        # liberally otherwise (like "HiTS: ...")
        schemes = ["http", "https", "ftp"]
        URI.extract(render, schemes) do |url|
          url_start = render.index(url)
          render = render[0, url_start] +
                   "<a href=\"" + url + "\">" +
                   render[url_start, url.length] +
                   "</a>" +
                   render[url_start + url.length, 1000000]
        end
        render
      end
    end
  end
end
